### ISSUE TITLE
MineChat.java:30 c95ea197335e769bbe313840383d9ec1184bce1c

### ISSUE THREAD

**Issue by jeffry1829** [jeffry1829/MineChat#1]
Unexpected exception while parsing console command "bind"
org.bukkit.command.CommandException: Unhandled exception executing command 'bind' in plugin MineChat v1.04
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[craftbukkit-1.7.5-R0.1-20140408.020329-16.jar:git-Bukkit-1.7.2-R0.3-14-g8f8716c-b3042jnks]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:180) ~[craftbukkit-1.7.5-R0.1-20140408.020329-16.jar:git-Bukkit-1.7.2-R0.3-14-g8f8716c-b3042jnks]
        at org.bukkit.craftbukkit.v1_7_R2.CraftServer.dispatchCommand(CraftServer.java:696) ~[craftbukkit-1.7.5-R0.1-20140408.020329-16.jar:git-Bukkit-1.7.2-R0.3-14-g8f8716c-b3042jnks]
        at org.bukkit.craftbukkit.v1_7_R2.CraftServer.dispatchServerCommand(CraftServer.java:683) [craftbukkit-1.7.5-R0.1-20140408.020329-16.jar:git-Bukkit-1.7.2-R0.3-14-g8f8716c-b3042jnks]
        at net.minecraft.server.v1_7_R2.DedicatedServer.ax(DedicatedServer.java:286) [craftbukkit-1.7.5-R0.1-20140408.020329-16.jar:git-Bukkit-1.7.2-R0.3-14-g8f8716c-b3042jnks]
        at net.minecraft.server.v1_7_R2.DedicatedServer.v(DedicatedServer.java:251) [craftbukkit-1.7.5-R0.1-20140408.020329-16.jar:git-Bukkit-1.7.2-R0.3-14-g8f8716c-b3042jnks]
        at net.minecraft.server.v1_7_R2.MinecraftServer.u(MinecraftServer.java:548) [craftbukkit-1.7.5-R0.1-20140408.020329-16.jar:git-Bukkit-1.7.2-R0.3-14-g8f8716c-b3042jnks]
        at net.minecraft.server.v1_7_R2.MinecraftServer.run(MinecraftServer.java:459) [craftbukkit-1.7.5-R0.1-20140408.020329-16.jar:git-Bukkit-1.7.2-R0.3-14-g8f8716c-b3042jnks]
        at net.minecraft.server.v1_7_R2.ThreadServerApplication.run(SourceFile:618) [craftbukkit-1.7.5-R0.1-20140408.020329-16.jar:git-Bukkit-1.7.2-R0.3-14-g8f8716c-b3042jnks]
Caused by: java.util.ConcurrentModificationException
        at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:859) ~[?:1.7.0_79]
        at java.util.ArrayList$Itr.next(ArrayList.java:831) ~[?:1.7.0_79]
        at org.twgogo.clouds.petjelinux.MineChat.onCommand(MineChat.java:30) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[craftbukkit-1.7.5-R0.1-20140408.020329-16.jar:git-Bukkit-1.7.2-R0.3-14-g8f8716c-b3042jnks]
        ... 8 more

**Comment by jeffry1829** [comment]
```
    for(ICommand el : arraylist){
        if( el.getName().equalsIgnoreCase(label) ){
            el.Execute(sender , args);
                return true;
        }
    }
```

**Comment by jeffry1829** [comment]
solved

**Comment by jeffry1829** [comment]
iterator.next() will throw exception
